"""
Tools for this recipe.

Auto-generated by praisonai recipe create.
"""

from praisonai_tools.tools import tavily_search, tavily_extract
from praisonaiagents.tools import internet_search
from praisonaiagents.tools import read_file, write_file, list_files

# Export tools for use in agents.yaml
TOOLS = [internet_search, read_file, tavily_search, write_file] if 'internet_search, read_file, tavily_search, write_file' else []


def get_all_tools():
    """Get all tools defined in this recipe."""
    return TOOLS
